name: Lerna Build Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Bootstrap monorepo
        run: lerna bootstrap --hoist

      - name: Build
        run: lerna run build --scope='{@starport/client-js,@starport/vue,@starport/vuex}'
