name: Test

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          github-token: ${{ secrets.GITUHB_TOKEN }} 
